### PR TITLE
[WIP] Add support for multiple I2C master and slave interfaces

### PR DESCRIPTION
**Pull request by manchoz**
Adding support for boards with multiple I2C interfaces.

Initial support for multiple Master I2C added: support for ESPs needs to be adapted and bring back.

### CODE REVIEW

**Comment by kwagyeman** [comment]
Hi, what defines WIRE_HOWMANY ?

**Comment by manchoz** [comment]
Hi, it's [defined](https://github.com/arduino/ArduinoCore-mbed/blob/83160bd98c8ec6d608e6c826b7736b0a3857490f/variants/PORTENTA_H7_M7/pins_arduino.h#L94) in the variants for mbed-based boards.

SAMD boards' equivalent is [`WIRE_INTERFACES_COUNT`](https://github.com/arduino/ArduinoCore-samd/blob/0b60a79c4b194ed2e76fead95caf1bbce8960049/variants/mkrgsm1400/variant.h#L118): I will add the proper conditional definitions where applicable in the next commits.

**Comment by kwagyeman** [comment]
Okay, but, that needs to be defined for ALL Arduino boards. Please check that.

**Comment by kwagyeman** [comment]
Is this ready?

**Review by kwagyeman — APPROVED** [review]

**Pull request merged**
